### ISSUE TITLE
Publish on SonaType Central Repository

### ISSUE THREAD

**Issue by ahmadsalim** [regb/scala-smtlib#19]
Have you considered publishing this library on [SonaType Central Repository](http://central.sonatype.org/)?
I think that it would be useful to have it as an ordinary library from SBT, instead of requiring to have it as a subproject (downloading it from GitHub).

Thanks!

**Comment by regb** [comment]
Hey. I was thinking of publishing at some point, but was still waiting until I was more confident about things staying stable from commit to commit.

But if that makes things more convenient, I can certainly publish the current version. I'll try to do that next week.

**Comment by ahmadsalim** [comment]
Great! :+1

**Comment by regb** [comment]
It should be working now with the following in build.sbt:
libraryDependencies += "com.regblanc" %% "scala-smtlib" % "0.2"
