### ISSUE TITLE
examples for algebraic data type (sum,tuple,etc)

### ISSUE THREAD

**Issue by doofin** [regb/scala-smtlib#47]
Hi , I can't find examples for uninterpreted sorts like tuples,would u like to provide some? Thanks!

**Comment by regb** [comment]
You would need to use the declare-sort command: https://github.com/regb/scala-smtlib/blob/master/src/main/scala/smtlib/trees/Trees.scala#L162

There's an example here with the smt2 format: https://github.com/regb/scala-smtlib/blob/master/src/it/resources/regression/smtlib/parsing/eq_diamond100.smt2

**Comment by doofin** [comment]
Thanks!
